# Book meta
title: "Introduction to Probability and Its Applications"
author: "Abdallah Alsammani"
logo: images/cover.png     # add a cover image here (optional)
copyright: "© {year} Abdallah Alsammani"

# Execution
execute:
  execute_notebooks: "auto"   # "off" while drafting if you prefer
  timeout: 60

only_build_toc_files: true

# HTML theme
html:
  favicon: images/favicon.png
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  baseurl: ""
  home_page_in_navbar: true
  navbar_number_sections: true
  extra_navbar: |
    <a href="https://mybinder.org/v2/gh/aalsammni/probability-activebook/HEAD" target="_blank">Run on Binder</a>
  extra_footer: |
    Built with <a href="https://jupyterbook.org">Jupyter Book</a>. Deployed via GitHub Pages.

# Repository buttons
repository:
  url: https://github.com/aalsammni/probability-activebook
  branch: main
  path_to_book: ""

# LaTeX/PDF (optional)
latex:
  latex_documents:
    targetname: book.tex

# Sphinx extensions (quiz/callouts)
sphinx:
  extra_extensions:
    - sphinx_exercise
    - sphinx_togglebutton

